# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('area', models.IntegerField(default=0)),
                ('vote_proxy', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('vote_main', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Agora.VoteMain')),
            ],
        ),
        migrations.CreateModel(
            name='VoteTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_name', models.CharField(max_length=200)),
                ('vote_m', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Agora.VoteMain')),
            ],
        ),
    ]
