# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 15:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCAT_CAT', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCHOICE_CHOICE', models.CharField(max_length=100)),
                ('PCHOICE_VOTES', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_CODE', models.CharField(max_length=200)),
                ('P_TITLE', models.CharField(max_length=100)),
                ('P_SHRBODY', models.CharField(max_length=300)),
                ('P_BODY', models.CharField(max_length=1000)),
                ('P_CREATION', models.DateTimeField(default=datetime.datetime(2017, 11, 12, 15, 48, 47, 147424, tzinfo=utc))),
                ('P_STARTDT', models.DateTimeField()),
                ('P_ENDDT', models.DateTimeField()),
                ('P_DURATION', models.IntegerField(default=0)),
                ('P_CODE2', models.CharField(blank=True, max_length=200)),
                ('PCAT_CAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eisegesis.PollCat')),
                ('UGRP_GROUPID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('USER_CREATORID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Polls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eisegesis.Polls')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pollchoice',
            name='polls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PChoice', to='Eisegesis.Polls'),
        ),
    ]
