# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-16 16:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Eisegesis', '0007_auto_20160816_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='P_CREATION',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 16, 16, 11, 52, 899642, tzinfo=utc)),
        ),
    ]
