# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-16 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Eisegesis', '0010_auto_20160816_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalchoice',
            name='proposals',
        ),
        migrations.AlterField(
            model_name='proposals',
            name='P_CREATION',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 16, 16, 27, 20, 68273, tzinfo=utc)),
        ),
    ]
