# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-16 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Eisegesis', '0012_auto_20160816_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalchoice',
            name='proposals',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Eisegesis.Proposals'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposals',
            name='P_CREATION',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 16, 16, 31, 18, 203363, tzinfo=utc)),
        ),
    ]
