# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Eisegesis', '0013_auto_20160816_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='P_CREATION',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 17, 15, 6, 11, 502910, tzinfo=utc)),
        ),
    ]
