# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Eisegesis', '0015_auto_20160904_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalchoice',
            name='proposals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PChoice', to='Eisegesis.Proposals'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='P_CREATION',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 11, 17, 9, 55, 168859, tzinfo=utc)),
        ),
    ]
