# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Eisegesis', '0016_auto_20160911_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='P_CREATION',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 11, 52, 47, 389352, tzinfo=utc)),
        ),
    ]
