# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 12:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Eisegesis', '0019_auto_20170402_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='P_CREATION',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 2, 12, 26, 25, 728696, tzinfo=utc)),
        ),
    ]
