# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 16:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Eisegesis', '0022_auto_20170403_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='proposals',
            name='P_CREATION',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 16, 59, 44, 386458, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='voter',
            name='Proposals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eisegesis.Proposals'),
        ),
        migrations.AddField(
            model_name='voter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
