# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 15:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Eisegesis', '0023_auto_20170403_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='P_CREATION',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 1, 15, 8, 56, 205360, tzinfo=utc)),
        ),
    ]
