# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 06:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Eisegesis', '0024_auto_20170801_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='P_CREATION',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 11, 6, 5, 0, 240074, tzinfo=utc)),
        ),
    ]
