# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Eisegesis', '0025_auto_20171111_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='P_CREATION',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 12, 13, 47, 41, 545964, tzinfo=utc)),
        ),
    ]
